AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Style/Documentation:
  Enabled: False